/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChopChopDevRouteImport } from './routes/chop-chop-dev'
import { Route as HostRouteImport } from './routes/host'
import { Route as JoinRouteImport } from './routes/join'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChopChopDevRoute = ChopChopDevRouteImport.update({
  id: '/chop-chop-dev',
  path: '/chop-chop-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chop-chop-dev': typeof ChopChopDevRoute
  '/host': typeof HostRoute
  '/join': typeof JoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chop-chop-dev': typeof ChopChopDevRoute
  '/host': typeof HostRoute
  '/join': typeof JoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chop-chop-dev': typeof ChopChopDevRoute
  '/host': typeof HostRoute
  '/join': typeof JoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chop-chop-dev' | '/host' | '/join'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chop-chop-dev' | '/host' | '/join'
  id: '__root__' | '/' | '/chop-chop-dev' | '/host' | '/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChopChopDevRoute: typeof ChopChopDevRoute
  HostRoute: typeof HostRoute
  JoinRoute: typeof JoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chop-chop-dev': {
      id: '/chop-chop-dev'
      path: '/chop-chop-dev'
      fullPath: '/chop-chop-dev'
      preLoaderRoute: typeof ChopChopDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChopChopDevRoute: ChopChopDevRoute,
  HostRoute: HostRoute,
  JoinRoute: JoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
